#ifndef UTIL_H_INCLUDED
#define UTIL_H_INCLUDED

enum EventType
{
    DISPLAY,
    KEYBOARD,
    MOUSECLICK,
    MOUSEDRAG,
};

struct Event
{
    EventType event;   /**< What is the event type from the EventType enum */
    unsigned char key; /**< Which key caused the keyevent */
    int button;        /**< Which button caused the event */
    int state;         /**< What state was the button in */
    int x;             /**< The x-coordinate of the event */
    int y;             /**< The y-coordinate of the event */
    int lastX;         /**< The x-coordinate of the last mouse down action */
    int lastY;         /**< The y-coordinate of the last mouse down action */

    /// This event is generated by the display callback
    Event() :
        event(DISPLAY) {}

    /// This event is generated by a keyboard event
    Event(unsigned char k, int xPos, int yPos) :
        event(KEYBOARD), key(k), x(xPos), y(yPos) {}

    /// This event is caused by a mouseclick
    Event(int b, int s, int xPos, int yPos) :
        event(MOUSECLICK), button(b), state(s), x(xPos), y(yPos) {}

    /// This event is generated by a mouse drag
    Event(int b, int xStart, int yStart, int xEnd, int yEnd) :
        event(MOUSEDRAG), button(b), x(xStart), y(yStart), lastX(xEnd), lastY(yEnd) {}
};

void initPalette();
void utilityCentral(Event event);
#endif // UTIL_H_INCLUDED
